version: "3"

services:
  api:
    depends_on:
      - "redis"
    build:
      context: ./app
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app/app:ro
      - ./images:/app/images
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - nginx-proxy
      - fv-internal

networks:
  nginx-proxy:
    external: true

  fv-internal:
    driver: bridge
